spring:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema/drop-legacy.sql
        - classpath:schema/maintenance_requests.sql
        - classpath:schema/properties.sql
        - classpath:schema/tenancies.sql
        - classpath:schema/documents.sql
        - classpath:schema/agents.sql
        - classpath:schema/users.sql
        - classpath:schema/invites.sql
  application:
    name: propti
  datasource:
    url: jdbc:postgresql://ep-holy-shape-abcvbtk6-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_W7edko3LZlYB
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true  # let JPA create/update, then run data.sql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
stack:
  api-url: https://api.stack-auth.com
  project-id: 89729a1c-ee23-4355-bc8c-45b0377a0e0d
  secret-server-key: ssk_t0sw697psttvahjhg9shpwj9graa34s2rabcd1ktpjmtg

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.propti.auth.filter.StackAuthenticationFilter: DEBUG
